### PR TITLE
Handle backwards compatibility for mac version check 

### PR DESCRIPTION
**Pull request by DemetriBairaktaris**

### CODE REVIEW

**Comment by DemetriBairaktaris** [comment]
@Ajordat Please review.

**Comment by Ajordat** [comment]
Could you explain what exactly is it addressing?

**Comment by DemetriBairaktaris** [comment]
It's accounting for this: https://stackoverflow.com/a/65402241/5714855

**Comment by Ajordat** [comment]
Why is it that the second commit does not check the `SYSTEM_VERSION_COMPAT` value? It seemed correct on the first commit. Is it to avoid the `os` import or something else?

**Comment by Ajordat** [comment]
Hi @DemetriBairaktaris let me know if you are interested in resuming this thread.

**Comment by Ajordat** [comment]
Closed without merging due to unresponsiveness.

**Pull request closed without merging**
